[package]
name = "charts-clean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irox-time = "0.4.2"
irox-log = "0.2.0"